"""2026-10-08 选题研究结果 → 每个选题一个 JSON（写入选题看板数据库）。

评分 = 需求 35% + 低竞争 25% + 趋势 15% + 频道契合 25%
  需求：vidIQ 核心词 volume 分数（0-100）；用代理词估算的选题打 8 折
  低竞争：100 - vidIQ competition
  趋势：50 + 增长率/4，限制在 0-100；无数据或代理词记 50
  频道契合：Claude 判断（受众、深度、与已有内容的衔接、合规风险）
"""
import json
import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "2026-10-08")
os.makedirs(OUT, exist_ok=True)

BERKSHIRE = {"label": "巴菲特 2013 年股东信", "url": "https://www.berkshirehathaway.com/letters/2013ltr.pdf"}

T = [
    dict(id="anthropic-ipo", category="AI 投資", timeliness="時事", deadline="2026-11 上市前",
         title="Anthropic 準備上市、估值上看 2 兆美元：普通人該不該搶？看懂 AI 巨頭 IPO 的估值、風險與 3 個判斷方法",
         angle="用 Claude 背後公司的 IPO 當案例，教觀眾看懂 IPO 估值、上市首日暴漲暴跌的規律，以及新股該不該追。",
         kw=dict(keyword="anthropic ipo", volume_score=74.7, volume_monthly=100602, competition=66.5, growth_pct=111.5,
                 note="全球數據；中文「anthropic 上市」搜尋量 <750，中文內容幾乎空白，先發優勢大。"),
         fit=92, keywords=["Anthropic", "Claude 上市", "AI IPO", "新股申購", "估值"],
         why_now="Reuters 報導最快 10 月中路演、11 月前上市；Bloomberg 稱最快 11 月中。搜尋量一個月翻倍，中文頻道還沒人系統講。",
         risks="上市日期與估值隨時變動，製作當天必須重新核實；不能暗示買入；分析師的高估說法要標明是觀點。",
         sources=[{"label": "CNBC：Anthropic IPO 時程延至 10 月中（2026-09-05）", "url": "https://www.cnbc.com/2026/09/05/anthropic-ipo-launch-shifts-toward-mid-october-reuters.html"},
                  {"label": "CNN：Anthropic 預計上市（2026-10-05）", "url": "https://www.cnn.com/2026/10/05/business/anthropic-ipo-stock-market"}]),
    dict(id="psychology-of-money", category="理財思維", timeliness="常青", deadline=None,
         title="《金錢心理學》精華：為什麼聰明人也存不到錢？7 個故事帶你看懂人和財富之間的心理陷阱，看完立刻改掉壞習慣",
         angle="把 Morgan Housel 的核心觀念（運氣與風險、夠了的藝術、複利、合理勝過理性）做成故事化說書，延續 EP001 的時間主題。",
         kw=dict(keyword="金錢心理學", volume_score=59.3, volume_monthly=9358, competition=24.9, growth_pct=None,
                 note="繁體關鍵詞競爭度僅 24.9，簡體「金钱心理学」5,068/月，英文書名 23.9 萬/月。"),
         fit=90, keywords=["金錢心理學", "心理帳戶", "行為經濟學", "說書", "存錢"],
         why_now="常青題材、競爭低，和 EP001 結尾「時間的秘密」直接銜接，適合做系列第二集。",
         risks="說書類需避免大段照搬原文，以自己的結構重述並標註出處。",
         sources=[{"label": "Morgan Housel〈How Warren Buffett Amassed His Fortune〉", "url": "https://csq.com/2020/08/how-warren-buffet-amassed-his-fortune/"}]),
    dict(id="crypto-basics", category="加密貨幣", timeliness="常青", deadline=None,
         title="加密貨幣新手完全指南：比特幣、以太幣、穩定幣到底差在哪？看完這集再決定要不要碰，避開 90% 新手會踩的坑",
         angle="不喊單、不預測價格，講清楚三種幣的本質差異、風險來源（波動、交易所、詐騙），以及新手該先問自己的問題。",
         kw=dict(keyword="加密貨幣", volume_score=61.4, volume_monthly=12969, competition=22.8, growth_pct=164.1,
                 note="台灣搜尋量 1.3 萬/月、成長 164%、競爭僅 22.8；「虛擬貨幣」競爭 19.9。"),
         fit=78, keywords=["加密貨幣", "比特幣", "以太幣", "穩定幣", "虛擬貨幣"],
         why_now="搜尋量近一個月成長 1.6 倍而競爭很低，是目前數據最好的機會之一。",
         risks="加密貨幣內容易觸發平台審查與詐騙聯想：不提供購買連結、不推薦交易所、強調高風險；「90% 新手」這類數字需有出處或改寫。",
         sources=[]),
    dict(id="tesla-q3", category="科技個股", timeliness="時事", deadline="2026-10-20 財報前",
         title="特斯拉交付量超預期、股價卻還跌 15%？財報前一次看懂特斯拉真正的估值故事：電動車、Robotaxi 與 Optimus",
         angle="拆解特斯拉估值由哪些故事支撐、哪些已經兌現、哪些還是預期，教觀眾用「業務拆分」的方法看任何熱門股。",
         kw=dict(keyword="特斯拉", volume_score=68.8, volume_monthly=40689, competition=62.8, growth_pct=665.6,
                 note="台灣「特斯拉」搜尋量暴增 666%；robotaxi、cybercab、optimus 全球搜尋量都很高。"),
         fit=75, keywords=["特斯拉", "Robotaxi", "Cybercab", "Optimus", "FSD", "馬斯克"],
         why_now="Q3 交付 486,532 輛超預期，財報約 10/20～10/21 公布（各來源日期不一），話題熱度最高的時候。",
         risks="競爭度高；財報日期需再核實；避免預測股價與給出買賣建議。",
         sources=[{"label": "Yahoo Finance：特斯拉 Q3 交付超預期", "url": "https://finance.yahoo.com/markets/stocks/article/tesla-stock-rises-as-company-reports-q3-deliveries-that-top-analyst-estimates-145514238.html"},
                  {"label": "Motley Fool：Why Tesla stock jumped（2026-10-02）", "url": "https://www.fool.com/investing/2026/10/02/why-tesla-stock-jumped-today/"}]),
    dict(id="us-stock-tax", category="美股入門", timeliness="常青", deadline=None,
         title="台灣人、香港人買美股到底要繳多少稅？股息預扣 30%、匯率成本、美國遺產稅一次看懂，別讓隱形成本吃掉你的報酬",
         angle="EP001 結尾承諾過的續集：非美國居民投資美股指數基金的稅與匯率成本，以及常見的降低成本做法。",
         kw=dict(keyword="美股投資", volume_score=53.0, volume_monthly=3568, competition=35.1, growth_pct=None,
                 note="以「美股投資」為代理詞；稅務長尾詞在 vidIQ 無資料。"),
         fit=95, keywords=["美股稅", "股息預扣稅", "遺產稅", "複委託", "匯率"],
         why_now="EP001 已在片中預告「之後專門做一集」，觀眾有期待，也能把觀眾導回 EP001。",
         risks="稅務規則依居住地不同，需分台灣、香港說明並引用官方資料；明確標註「非稅務建議」。",
         sources=[]),
    dict(id="sp500-vs-nasdaq", category="指數投資", timeliness="常青", deadline=None,
         title="標普500 vs 納斯達克100：到底該買哪一個？用 30 年歷史數據看懂兩大指數的差別、報酬與風險，新手不再選錯",
         angle="比較兩個指數的組成、產業集中度、歷史報酬與最大跌幅，讓觀眾知道選擇背後的取捨。",
         kw=dict(keyword="s&p500", volume_score=76.0, volume_monthly=123157, competition=62.5, growth_pct=-7.4,
                 note="英文詞全球數據；VOO 3.4 萬/月、競爭 41.9。繁體長尾詞資料少。"),
         fit=88, keywords=["標普500", "納斯達克", "VOO", "QQQ", "指數基金"],
         why_now="承接 EP001 的指數基金主題，是觀眾看完最自然的下一個問題。",
         risks="不推薦特定 ETF 代號為買入標的；歷史數據需標明來源與期間。",
         sources=[BERKSHIRE]),
    dict(id="couch-potato", category="指數投資", timeliness="常青", deadline=None,
         title="沙發土豆投資法：一年只花 30 分鐘、完全不用看盤，這個懶人投資組合長期贏過多數基金經理人，新手照著做就能開始",
         angle="介紹沙發土豆組合的由來、股債配置與再平衡，用回測數據呈現它在大跌年的表現。",
         kw=dict(keyword="指数基金", volume_score=52.6, volume_monthly=3350, competition=25.4, growth_pct=None,
                 note="「沙發土豆」在 vidIQ 無資料，以簡體「指数基金」為代理詞，競爭低。"),
         fit=86, keywords=["沙發土豆", "懶人投資", "股債配置", "再平衡", "被動投資"],
         why_now="使用者指定的核心關鍵詞，常青、競爭低，與 EP001 形成指數投資系列。",
         risks="「贏過多數基金經理人」需用 SPIVA 等數據佐證，否則改寫；回測不代表未來。",
         sources=[]),
    dict(id="dca-vs-lump-sum", category="指數投資", timeliness="常青", deadline=None,
         title="手上有一筆錢，該一次投入還是定期定額？用歷史數據告訴你答案，還有讓你睡得著覺的折衷做法",
         angle="用歷史數據比較一次投入與分批投入的勝率與心理成本，給出不同情況下的做法。",
         kw=dict(keyword="財務自由", volume_score=54.4, volume_monthly=4396, competition=43.2, growth_pct=None,
                 note="「定期定額」在 vidIQ 無資料，暫以理財類相關詞估算，需求分數偏保守。"),
         fit=88, keywords=["定期定額", "一次投入", "分批買進", "投資心理", "Vanguard 研究"],
         why_now="EP001 強調「分批買進」，觀眾會接著問「那手上的一筆錢怎麼辦」。",
         risks="需引用可信研究（如 Vanguard）並說明期間與市場；避免絕對化結論。",
         sources=[BERKSHIRE]),
    dict(id="ai-investing-layers", category="AI 投資", timeliness="常青", deadline=None,
         title="AI 投資入門：不押單一股票，普通人怎麼參與 AI 浪潮？一張圖看懂晶片、雲端、應用三層產業鏈，避開追高陷阱",
         angle="把 AI 產業拆成三層，說明各層的賺錢方式與風險，連結到指數與分散投資，而不是追熱門股。",
         kw=dict(keyword="ai投資", volume_score=61.1, volume_monthly=12380, competition=42.6, growth_pct=-62.1,
                 note="搜尋量 1.2 萬/月，近一個月比基準下滑，但仍屬高需求。"),
         fit=84, keywords=["AI投資", "輝達", "台積電", "雲端", "AI ETF"],
         why_now="AI 是使用者核心關鍵詞，也能為 Anthropic、輝達等時事題做知識鋪墊。",
         risks="提到個股時只作產業說明，不給買賣建議。",
         sources=[]),
    dict(id="spacex-after-ipo", category="科技個股", timeliness="時事", deadline=None,
         title="SpaceX 上市四個月：史上最大 IPO 之後，2 兆美元的太空公司值不值？看懂 Starlink 怎麼賺錢，以及新股上市後的常見走勢",
         angle="用 SpaceX 案例講 IPO 後的鎖定期、估值與真實業務（Starlink 是唯一獲利部門），教觀眾冷靜看待熱門新股。",
         kw=dict(keyword="spacex", volume_score=90.5, volume_monthly=1150341, competition=71.7, growth_pct=54.0,
                 note="全球數據；繁體「spacex 上市」4,537/月、競爭 66。"),
         fit=74, keywords=["SpaceX", "SPCX", "Starlink", "IPO", "鎖定期"],
         why_now="SpaceX 已於 2026-06-12 上市（SPCX），全球搜尋量仍在成長；可與 Anthropic IPO 做成新股系列。",
         risks="上市後股價與估值需製作當天核實；鎖定期到期日要查證。",
         sources=[{"label": "CNBC：SpaceX IPO 首日收 161 美元（2026-06-12）", "url": "https://www.cnbc.com/2026/06/12/spacex-ipo-spcx-live-updates.html"},
                  {"label": "CNBC：SpaceX 募資 750 億美元", "url": "https://www.cnbc.com/2026/06/11/spacex-raises-75-billion-in-record-setting-ipo-ahead-of-nasdaq-debut.html"}]),
    dict(id="naval", category="理財思維", timeliness="常青", deadline=None,
         title="《納瓦爾寶典》精華：不靠運氣也能致富的 5 個原則，看懂槓桿、專長與複利，普通上班族也能開始用",
         angle="把納瓦爾的財富觀（專長、槓桿、擁有權、長期遊戲）用故事和例子講清楚，給出可行動的清單。",
         kw=dict(keyword="納瓦爾寶典", volume_score=62.0, volume_monthly=14229, competition=44.3, growth_pct=-39.0,
                 note="1.4 萬/月，已有多個說書頻道做過（樊登、張修修等），需要差異化角度。"),
         fit=80, keywords=["納瓦爾寶典", "納瓦爾", "說書", "財富自由", "槓桿"],
         why_now="使用者指定的核心關鍵詞，需求穩定。",
         risks="已有大量說書影片，需以「投資人視角」做出差異；避免照搬書中段落。",
         sources=[]),
    dict(id="stablecoin-circle", category="加密貨幣", timeliness="時事", deadline=None,
         title="穩定幣到底是什麼？從 Circle 看懂 USDC 怎麼賺錢、美國 GENIUS 法案的影響，以及 21 家大銀行為什麼要搶這門生意",
         angle="用 Circle 的商業模式講穩定幣如何靠儲備利息獲利，再看監管與銀行聯盟帶來的競爭。",
         kw=dict(keyword="加密貨幣", volume_score=61.4, volume_monthly=12969, competition=22.8, growth_pct=164.1,
                 note="以「加密貨幣」為代理詞；Circle 相關中文詞在 vidIQ 無資料。"),
         fit=72, keywords=["穩定幣", "Circle", "USDC", "GENIUS 法案", "CRCL"],
         why_now="9/1 二十一家金融機構宣布籌組美元穩定幣公司；GENIUS 法案 2027 年 1 月生效。",
         risks="最新進展需核實（Arc 主網是否上線等）；不推薦 CRCL 股票。",
         sources=[{"label": "TIKR：Circle 股價與催化劑", "url": "https://www.tikr.com/blog/circle-stock-rose-5-friday-heres-what-could-drive-crcl-in-2026"}]),
    dict(id="nvidia-empire", category="科技個股", timeliness="時事", deadline=None,
         title="黃仁勳的 AI 帝國還能走多遠？看懂輝達為什麼能賺這麼多錢，以及投資 AI 龍頭股最容易忽略的 3 個風險",
         angle="拆解輝達的護城河（CUDA 生態、資料中心）與集中度風險，教觀眾分辨「好公司」與「好價格」。",
         kw=dict(keyword="黃仁勳", volume_score=60.4, volume_monthly=11128, competition=71.0, growth_pct=240.6,
                 note="「黃仁勳」成長 240%，但「輝達」競爭度 74，偏高。"),
         fit=70, keywords=["輝達", "黃仁勳", "NVIDIA", "AI 晶片", "台積電"],
         why_now="黃仁勳搜尋量近一個月成長 2.4 倍。",
         risks="市值 6 兆等說法僅見於低可信度來源，製作時需用可靠數據；競爭激烈需強差異化。",
         sources=[]),
    dict(id="crash-playbook", category="美股入門", timeliness="常青", deadline=None,
         title="美股崩盤時該怎麼辦？從 2000、2008、2020 三次大跌學會不被嚇跑的方法，下次恐慌來臨前先看這集",
         angle="回顧三次大跌的跌幅與恢復時間、當時的新聞氛圍，以及事後看來最好與最差的反應。",
         kw=dict(keyword="做空美股", volume_score=58.0, volume_monthly=7624, competition=26.6, growth_pct=None,
                 note="「美股崩盤」<750；以「做空美股」為情緒相近的代理詞。"),
         fit=82, keywords=["美股崩盤", "股災", "熊市", "長期投資", "恐慌"],
         why_now="常青題材，任何一次市場大跌都會讓它重新被搜尋；可預先做好。",
         risks="歷史跌幅與恢復時間需查證；避免製造恐慌的標題用語。",
         sources=[BERKSHIRE]),
    dict(id="mental-accounting", category="理財思維", timeliness="常青", deadline=None,
         title="為什麼年終獎金總是一下就花光？行為經濟學的「心理帳戶」告訴你原因，學會這招輕鬆多存下一筆錢",
         angle="用生活例子解釋心理帳戶、損失趨避等偏誤，給出可執行的存錢方法。",
         kw=dict(keyword="心理帳戶", volume_score=54.1, volume_monthly=4235, competition=26.3, growth_pct=None,
                 note="「行為經濟學」4,351/月、競爭 23.6。"),
         fit=76, keywords=["心理帳戶", "行為經濟學", "存錢", "年終獎金", "損失趨避"],
         why_now="常青、低競爭；年終獎金季（年底）前發布效果更好。",
         risks="引用的研究需標明出處。",
         sources=[]),
    dict(id="fire-number", category="理財思維", timeliness="常青", deadline=None,
         title="財務自由到底需要多少錢？用 4% 法則 3 分鐘算出你的數字，以及這個法則沒告訴你的 3 個風險",
         angle="解釋 4% 法則的來源（Trinity 研究）、計算方式與限制，讓觀眾算出自己的目標。",
         kw=dict(keyword="財務自由", volume_score=54.4, volume_monthly=4396, competition=43.2, growth_pct=None,
                 note="繁體「財務自由」4,396/月。"),
         fit=78, keywords=["財務自由", "4% 法則", "FIRE", "退休金", "提領率"],
         why_now="常青題材，情緒共鳴強，適合做成互動式計算說明。",
         risks="4% 法則基於美國歷史數據，需說明對其他市場與時期的適用限制。",
         sources=[]),
    dict(id="us-stock-first-etf", category="美股入門", timeliness="常青", deadline=None,
         title="美股新手第一課：從開戶到買下第一支 ETF，一集看懂所有步驟與費用，看完今天就能開始",
         angle="以流程圖說明開戶管道（複委託、海外券商）、費用比較與下單步驟，不推薦特定券商。",
         kw=dict(keyword="美股投資", volume_score=53.0, volume_monthly=3568, competition=35.1, growth_pct=None,
                 note="簡體「美股投资」數據；繁體長尾詞資料少。"),
         fit=74, keywords=["美股開戶", "複委託", "海外券商", "ETF", "新手"],
         why_now="實用型長青內容，能承接指數投資系列的觀眾。",
         risks="券商資訊變動快且涉及商業推薦，需中立並註明查核日期。",
         sources=[]),
    dict(id="paypay-japan", category="投資平台", timeliness="時事", deadline=None,
         title="PayPay 在美國上市、日本人瘋買美股：從新 NISA 熱潮看懂亞洲散戶的投資轉變，台灣人可以學的 3 件事",
         angle="以 PayPay 3 月在納斯達克上市與日本散戶投資美股的熱潮為切入，談制度如何影響散戶行為。",
         kw=dict(keyword="投資", volume_score=83.1, volume_monthly=368467, competition=60.3, growth_pct=-8.5,
                 note="「投資」搜尋主要來自日本（93%）；「PayPay 證券」本身中文需求不明，受眾契合度存疑。"),
         fit=48, keywords=["PayPay", "PayPay 證券", "新 NISA", "日本散戶", "美股"],
         why_now="PayPay 母公司已於 2026-03-12 在納斯達克上市。",
         risks="與繁體中文受眾關聯較弱；PayPay 證券 2026 年的最新服務資訊未能查到，需確認。",
         sources=[{"label": "株探：PayPay 上場（2026-03）", "url": "https://us.kabutan.jp/stocks/PAYP/news/n202603130002"}]),
]


# 核心词不是选题本身、只是相近词的选题（数据仅供参考）
PROXY = {"us-stock-tax", "couch-potato", "dca-vs-lump-sum", "stablecoin-circle", "crash-playbook", "paypay-japan", "us-stock-first-etf"}


def clamp(x):
    return max(0, min(100, x))


for t in T:
    k = t["kw"]
    proxy = t["id"] in PROXY
    demand = round(k["volume_score"] * (0.8 if proxy else 1))
    comp = round(100 - k["competition"])
    trend = 50 if proxy else round(clamp(50 + (k["growth_pct"] / 4 if k["growth_pct"] is not None else 0)))
    score = round(0.35 * demand + 0.25 * comp + 0.15 * trend + 0.25 * t["fit"])
    doc = {
        "title": t["title"], "angle": t["angle"], "category": t["category"],
        "timeliness": t["timeliness"], "deadline": t["deadline"],
        "keywords": t["keywords"], "why_now": t["why_now"], "risks": t["risks"], "sources": t["sources"],
        "metrics": {"keyword": k["keyword"], "volume_monthly": k["volume_monthly"], "competition": k["competition"],
                    "growth_pct": k["growth_pct"], "note": k["note"]},
        "scores": {"demand": demand, "competition": comp, "trend": trend, "fit": t["fit"]},
        "score": score, "proxy_keyword": proxy, "status": "候選", "created": "2026-10-08", "episode": None,
    }
    json.dump(doc, open(os.path.join(OUT, t["id"] + ".json"), "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print(f"{score:3d}  {t['id']}")
